extends: ["spectral:oas", "spectral:asyncapi"]
functions: [validatesWhetherMandatoryFieldsAreDefined, validatesIfMinItemsIsZeroForRequiredArrayField, validatesIfMinItemsIsOneForNotRequiredArrayField]

rules:
  valid-required-defined-properties:
    message: "{{error}}"
    severity: error
    given: 
      - $..[?(@.type == 'object' && @.required)]
    then:
      function: "validatesWhetherMandatoryFieldsAreDefined"

  valid-minItems-array-required:
    message: "{{error}}"
    severity: warn
    given: 
      - $..[?(@.type == 'object' && @.required)]
    then:
      function: "validatesIfMinItemsIsZeroForRequiredArrayField"

  valid-minItems-array-not-required:
    message: "{{error}}"
    severity: warn
    given: 
      - $..[?(@.type == 'object' && @.required)]
    then:
      function: "validatesIfMinItemsIsOneForNotRequiredArrayField"
