extends: ["spectral:oas", "spectral:asyncapi"]
functions: [validRequired, validMinItemsArray]

rules:
  valid-required-defined-properties:
    message: "{{error}}"
    severity: error
    given: 
      - $..schemas
    then:
      function: "validRequired"

  valid-minItems-array:
    message: "{{error}}"
    severity: warn
    given: 
      - $..schemas
    then:
      function: "validMinItemsArray"
