extends: ["spectral:oas", "spectral:asyncapi"]
functions: [validatesWhetherMandatoryFieldsAreDefined, validMinItemsArray]

rules:
  valid-required-defined-properties:
    message: "{{error}}"
    severity: error
    given: 
      - $..[?(@.type == 'object' && @.required)]
    then:
      function: "validatesWhetherMandatoryFieldsAreDefined"

  # valid-minItems-array:
  #   message: "{{error}}"
  #   severity: warn
  #   given: 
  #     - $..schemas
  #   then:
  #     function: "validMinItemsArray"
